### ISSUE TITLE
WebSVN scraping fails

### ISSUE THREAD

**Issue by marcink** [cosmocode/dokuwiki-plugin-scrape#3]
I attempted to scrape a file listing on WebSVN server.  Instead of the WebSVN file listing, I get an XML response that appears to be SVN's internal protocol.

SVN uses the same server (and URL) addresses for svn client accesses and for the WebSVN front end, so I am assuming the server distinguishes what to serve by some detail in the request, perhaps client type?

I also observed that requesting page source from Firefox also returns the same XML structure, but inspecting the page reveals the HTML that was served.

Any idea how to work around this?

**Comment by splitbrain** [comment]
Judging from "I also observed that requesting page source from Firefox also returns the same XML structure, but inspecting the page reveals the HTML that was served." I would guess that websvn alsways serverd XML and used an XSLT stylesheet to convert it into HTML in browsers. This won't ever be supported in this plugin.

Probabably irrelevant by now anyway ;-)

**Comment by marcink** [comment]
"Probabably irrelevant by now anyway ;-)" - agreed.  It has been a while since I had access to the instances I worked on ... wow ... 6 years ago
