### ISSUE TITLE
Php 8, syntax issues, HTMLPurifier.standalone and phpQuery-onefile.php

### ISSUE THREAD

**Issue by pblahman** [cosmocode/dokuwiki-plugin-scrape#4]
My hope is the changes indicated below will find their way into the source.
I am not sure this is the "right/correct" repository for this issue.
This issue is:  Dokuwiki will fail to start without the changes indicated below.

Issues with Php 8, Dokuwiki version Jack Jackrum. 
 I edited two files in the scrape module. I changed the {}(elipses) to [] brackets on the lines indicated below. Here are the lines I changed.

HTMLPurifier.standalone.php:// PBL $in = ord($str{$i});
HTMLPurifier.standalone.php: // PBL if ($raw{0} != '(') {
HTMLPurifier.standalone.php:// PBL if ($attr['size']{0} == '+' || $attr['size']{0} == '-') {

phpQuery-onefile.php:// PBL if ($param{0} == 'n')
phpQuery-onefile.php:// PBL else if (mb_strlen($param) > 1 && $param{1} == 'n')

These changes got me past the "does not work" problem. There are still some "warnings" in the log files that need attention/resolution.   I am working on finding the "right place" to report of "fix" the warnings.

[root@phil-osophical scrape]# php --version
PHP 8.0.27 (cli) (built: Jan  3 2023 16:17:26) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies

[root@phil-osophical scrape]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"

**Comment by splitbrain** [comment]
obsoleted by #5
