### ISSUE TITLE
Cache for scrape data

### ISSUE THREAD

**Issue by xube** [cosmocode/dokuwiki-plugin-scrape#7]
### Feature Description

Firstly let me thank you for a great plugin, it is really what i was looking for.

But i would like to know if there is possibility cache scraped data. Right now It scrapes data on every load of a page. I would like to scrape data just if it is really necessary. For example once per week or month. Is it possible?

Maybe it could be like this:
`{{scrape>url query|title|time#lasttimestamp}}`

This will try load scraped data only if the actual server time is more (based on time which could be in seconds) than last timestamp.

Also is there any way how we could save scraped values as some kind meta data? For example with struct or sqlite plugin?
Thank you

**Comment by splitbrain** [comment]
The scraping takes place during page rendering. The results are cached with the page. You can influence how long rendered pages are cached with the cachetime setting in DokuWiki
